name = "spag_lapack"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = " "
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
