name = "spag_lapack"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2022 John S. Urban"
description = "Experimental LAPACK version"
categories = ["lapack"]
keywords = ["fortran", "linear algebra"]
homepage = "https://github.com/urbanjost/spag_lapack.git"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true

#[[test]]
#[test.dependencies]

[dependencies]
test_aux = { path = "test_aux"} 
#M_kracken      = { git = "https://github.com/urbanjost/M_kracken.git" }
#M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
