name = "M_tst"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = true
[install]
   library = false
[fortran]
   # new
   #implicit-typing = false
   #implicit-external = false
   #source-form = "free"
   # traditional
   implicit-typing = true
   implicit-external = true
   source-form = "default"
