!*==intfaces.f90  created by SPAG 7.51RB at 21:36 on  3 Mar 2022
MODULE S_XERBLA_ARRAY
   INTERFACE
      SUBROUTINE XERBLA_ARRAY(Srname_array,Srname_len,Info)
      IMPLICIT NONE
      CHARACTER(1) , INTENT(IN) , DIMENSION(Srname_len) :: Srname_array
      INTEGER , INTENT(IN) :: Srname_len
      INTEGER :: Info
      END SUBROUTINE XERBLA_ARRAY
   END INTERFACE
END MODULE S_XERBLA_ARRAY
!*==intfaces.f90  created by SPAG 7.51RB at 21:36 on  3 Mar 2022
MODULE S_XERBLA
   INTERFACE
      SUBROUTINE XERBLA(Srname,Info)
      IMPLICIT NONE
      CHARACTER(*) , INTENT(IN) :: Srname
      INTEGER , INTENT(IN) :: Info
      END SUBROUTINE XERBLA
   END INTERFACE
END MODULE S_XERBLA
